version: '3'
services:
  frontend:
    build:
      context: ./demo
    image: sumithaapvr/demo-app
    ports:
      - "4812:80"

  backend:
    build:
      context: ./backend
    image: sumithaapvr/backend-app
    ports:
      - "5000:5000"
