version: '3'
services:
  backend:
    build:
      context: ./backend
    image: sumithaapvr/backend-app
    ports:
      - "5000:5000"
    container_name: backend
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/book_recommendation  # 

  frontend:
    build:
      context: ./demo
      args:
        REACT_APP_API_URL: http://backend:5000
    image: sumithaapvr/demo-app
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongodb:  
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
