version: '3'
services:
  backend:
    build:
      context: ./backend
    image: sumithaapvr/backend-app
    ports:
      - "5000:5000"
    container_name: backend

  frontend:
    build:
      context: ./demo
    image: sumithaapvr/demo-app
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000
